elastic.hash: changeme
elastic.roles:
    - admin

superadmin.hash: superadmin
superadmin.roles:
    - admin

kibanaserver:
    hash: $2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.
    #password is: kibanaserver
kibanaserver.roles:
    - kibana_user
