admin:
  cluster:
    - ALL
  indices:
    "*":
      "*":
        - ALL

kibana_user:
  cluster:
    - MONITOR
  indices:
    '?kibana':
      '*':
        - INDEX_ALL

read_only:
  indices:
    '*':
      '*':
        - READ
