cluster.name: elasticsearch
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1

searchguard:
    ssl:
        transport:
            enabled: true
            keystore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/node-0-keystore.jks
            keystore_password: changeme
            truststore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/truststore.jks
            truststore_password: changeme
            enforce_hostname_verification: false
        http:
            enabled: true
            keystore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/node-0-keystore.jks
            keystore_password: changeme
            truststore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/truststore.jks
            truststore_password: changeme
            # clientauth_mode: REQUIRE
            # http.clientauth_mode: REQUIRE
    authcz.admin_dn:
    - "CN=elastic ,OU=devops, C=COM"
